#ifndef H_TARGETS_TARGET_
#define H_TARGETS_TARGET_


/* Kinetis K64F flash partitioning.
 * Firmware Entry point at 0x8100
 */
#define WOLFBOOT_SECTOR_SIZE			    0x1000
#define WOLFBOOT_PARTITION_SIZE			    0x7A000

#define WOLFBOOT_PARTITION_BOOT_ADDRESS     0xA000
#define WOLFBOOT_PARTITION_UPDATE_ADDRESS   0x84000
#define WOLFBOOT_PARTITION_SWAP_ADDRESS     0xff000

#endif
